################################################################################
#
#ALEXA
#
################################################################################
  smart_home:
    filter:
      include_entities:
        - vacuum.xiaomi_vacuum
        - script.restart_home_assistant
        # - script.reboot_os
        # - script.ac_turn_off
        # - script.ac_turn_on
        # - script.ac_fan_speed
        # - input_boolean.ac_status_alexa
        - binary_sensor.xiaomi_motion_sensor_hallway
        - sensor.humidity_bedroom_0
        - sensor.temperature_bedroom_0
        - sensor.xiaomi_gateway_illumination
        
        - binary_sensor.door_sensor_bedroom
        - binary_sensor.door_sensor_main_entrance
        - sensor.sensibo1_humidity
        - sensor.sensibo1_temp
      include_domains:
        - light
        - switch
        # - climate #Not in Use (using sensibo skill) 
      exclude_entities:
        - light.yeelight_white_f0b4290e4e68 #Duplicate
        - light.yeelight_rgb_286c07106e1b #Duplicate
        - light.bedroom_fan_light
        - switch.tv_lg_hdmi1
        - switch.tv_lg_hdmi2
        - switch.tv_lg_hdmi3
        - switch.ha_dockermon_cloud9ide
        - switch.ha_dockermon_hadockermon
        - switch.ha_dockermon_heimdall
        - switch.ha_dockermon_letsencrypt
        - switch.ha_dockermon_unifi
        - switch.ha_dockermon_unms
        
    entity_config:
      ############## GENERAL
      vacuum.xiaomi_vacuum:
        name: Robik
        description: The Xiaomi Vacuum Cleaner 
        display_categories: OTHER
      ############## LIGHTS
      #all light. get "display_categories: LIGHT"  by default
      light.sonoff_light:
        name: Kitchen
        description: The light in the kitchen
        
      light.desk_lamp:
        name: Bedroom
        description: The Bed side light in Bedroom
        
      light.gateway_light_34ce0088d2f7:
        name: Gateway
        description: The light in the Xiaomi Gateway Hub
        
      light.living_room_color_bulb:
        name: Right Bulb
        description: The Right light in the Living room
      
      light.white_bulb:
        name: Left Bulb
        description: The Left light in the Living room
        
      light.philips_bulb:
        name: Service #Philips Bulb
        description: The light in the Service Corner
        
      light.sonoff_hallway_light:
        name: MISSDARON 
        description: The light in the Hallway
      ##############SWITCH
      #all switch. get "display_categories: SWITCH"  by default
      switch.mqtt_pow2:
        name: Kitchen Camera
    
      switch.sonoff_xiaomicctv_switch:
        name: Salon Camera

        
      switch.xiaomi_powerstrip:
        name: Power Strip
        
      switch.tv_lg:
        name: TV
        
      switch.tv_lg_vol:
        name: Volume TV #"Alexa, turn on Volume TV" "Alexa, turn off Volume TV"
        
      switch.tv_lg_mute:
        name: Mute TV #"Alexa, turn on "Mute TV" "Alexa, turn off "Mute TV"
      # input_boolean.ac_status_alexa:
      #   name: AC
      #   display_categories: SWITCH

        
      # sensor.temperature_bedroom_0:
      #     name: Temperature 
      #   description: The Temperature in the living room
      #   display_categories: TEMPERATURE_SENSOR
        
      # sensor.humidity_bedroom_0:
      #     name: Humidity 
      #   description: The Humidity in the living room
      #   display_categories: OTHER
        
      ##############SCRIPTS - all script. get "Applies to Scenes"  by default
      # script.reboot_os:
      #   name: Reboot OS
      script.restart_home_assistant:
        name: Restart Home Assistant
      # script.ac_turn_off:
      #   name: AC off
      # script.ac_turn_on:
      #   name: AC on
      # script.ac_fan_speed:
      #   name: AC Speed
      # group.allmylights:
      #   name: All My Lights
    # https://developer.amazon.com/docs/device-apis/alexa-discovery.html#display-categories
         ##############BINARY SENSORS and SENSORS
      binary_sensor.xiaomi_motion_sensor_hallway:
        name: Hallway motion
      sensor.humidity_bedroom_0:
        name: Bedroom Humidity
      sensor.temperature_bedroom_0:
        name: Bedroom Temperature
      sensor.xiaomi_gateway_illumination:
        name: Gateway illumination
      binary_sensor.door_sensor_bedroom:
        name: Bedroom door
      binary_sensor.door_sensor_main_entrance:
        name: Main door
      sensor.sensibo1_humidity:
        name: Living room Humidity
      sensor.sensibo1_temp:
        name: Living room Temperature
